name = "maps-metadata"
main = "src/index.ts"
compatibility_date = "2023-04-18"
account_id = "5e015123d861c65819b733acb27db18e"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "maps-metadata-prod-3462"
preview_bucket_name = "maps-metadata-dev-3462"

[[routes]]
pattern = "maps-metadata.beyondallreason.dev"
custom_domain = true
