// Script generating map presets and map battle presets for SPADS. Those
// presets are setting modoptions per map on the server side.

import fs from 'node:fs/promises';
import { program } from '@commander-js/extra-typings';
import { MapModoptions } from '../../../gen/types/map_modoptions.js';
import { readMapModoptions } from './maps_metadata.js';

const AUTOMATED_HEADER = `#
# AUTOMATICALLY GENERATED FILE, DO NOT EDIT!
#
# This file is automatically generated from the beyond-all-reason/maps-metadata repository and any
# changes here will be overridden by the next update. If you want to make any changes please follow
# https://github.com/beyond-all-reason/maps-metadata/wiki/Adding-a-created-map-to-the-game
#
`;

// Modoptions that SPADS must reset to their default on every map change, but which are not part of
// the map metadata. Format is `key:valueSpec`; SPADS applies the first '|'-separated entry and uses
// the whole list as the allowed-value set, so the spec can't be dropped: a bare `key:` would make
// every later `!bSet key <value>` be rejected as not allowed by the battle preset.
//
// Keep in sync with the [team]/[ffa]/[coop]/[duel]/[tourney] declarations in
// spads_config_bar/etc/battlePresets.conf. Those are what make the option settable at all, this is
// only what resets it on map change. Both are required.
const EXTRA_RESET_MODOPTIONS = [
    'mapmetadata_startbox_override:|~[A-Za-z0-9\\-\\_]*',
];

function genPresets(mapModoptions: MapModoptions[]): [string, string] {
    let preset =
`${AUTOMATED_HEADER}
[_DEFAULT_.smf] (transparent)
battlePreset:map_DEFAULT
`;

    let battlePreset =
`${AUTOMATED_HEADER}
[map_DEFAULT] (transparent)
${Array.from(new Set(mapModoptions.flatMap(m => Object.keys(m.modoptions))))
    .map(k => `${k}:`)
    .concat(EXTRA_RESET_MODOPTIONS)
    .join('\n')}
`;

    for (const m of mapModoptions) {
        const battlePresetName = 'map_' + m.springName.replace(/[^a-zA-Z0-9_]/g, '_');

        preset +=
`
[${m.springName}.smf] (transparent)
battlePreset:${battlePresetName}
`;

        // Inherit from map_DEFAULT so that all the keys this map doesn't set are reset to their
        // default value on map change: SPADS only touches the settings a battle preset names.
        battlePreset +=
`
[${battlePresetName}<map_DEFAULT>] (transparent)
${Object.entries(m.modoptions).map(([k, v]) => `${k}:${v}`).join('\n')}
`;
    }

    return [preset, battlePreset];
}

const prog = program
    .argument('<mapPresets>', 'Map presets output path.')
    .argument('<mapBattlePresets>', 'Map battle presets output path.')
    .parse();
const [mapPresetsPath, mapBattlePresetsPath] = prog.processedArgs;
const [mapPresets, mapBattlePresets] = genPresets(await readMapModoptions());
await fs.writeFile(mapPresetsPath, mapPresets);
await fs.writeFile(mapBattlePresetsPath, mapBattlePresets);
