/* eslint-disable */
/**
 * This file was automatically generated by gen_webflow_types.ts.
 * DO NOT MODIFY IT BY HAND. Instead, run make refresh_webflow_types
 */

/**
 * This interface was referenced by `undefined`'s JSON-Schema
 * via the `definition` "mapFieldsRead".
 */
export interface WebflowMapFieldsRead {
  rowyid?: string;
  minimap?: WebflowImageRef;
  minimapurl?: string;
  /**
   * Map width in elmos
   */
  width?: number;
  /**
   * Map height in elmos
   */
  height?: number;
  /**
   * Downlink to BAR CDN
   */
  downloadurl?: string;
  /**
   * Main Title / Slogan / Tagline - not the name of the map.
   */
  title?: string;
  /**
   * Extra optional subtitle to support the main Title.
   */
  subtitle?: string;
  /**
   * Long-text for describing the map, gameplay, and unique features
   */
  description?: string;
  /**
   * The mapper that made this map
   */
  author?: string;
  /**
   * Unique Sketchfab Identifier that will be used if there is a 3D sketchfab version available.
   */
  sketchfabcode?: string;
  "bg-image"?: WebflowImageRef;
  "perspective-shot"?: WebflowImageRef;
  "more-images"?: WebflowImageRef[];
  "wind-min"?: number;
  "wind-max"?: number;
  "tidal-strength"?: number;
  /**
   * Maximum players or startpositions for this map
   */
  "max-players"?: number;
  /**
   * Total amount of teams that can spawn / amount of (max.) preset startboxes or amount of AllyTeams.
   */
  "team-count"?: number;
  /**
   * store json with all sync related state serialized
   */
  syncstate?: string;
  /**
   * Simple textfield which should hold "gametype1, gametype2" - the simple solution for GameTypes
   */
  "game-types"?: string;
  /**
   * Reference Field for "Map Tags" which should hold the "itemID", "itemID" when linking multiple tags to this map
   */
  "game-tags-ref-2"?: string[];
  "mini-map"?: WebflowImageRef;
  "metal-map"?: WebflowImageRef;
  "height-map"?: WebflowImageRef;
  /**
   * Surface of the map (W * H)
   */
  mapsize?: number;
  name: string;
  slug: string;
  _archived: boolean;
  _draft: boolean;
  "created-on"?: string;
  "updated-on"?: string;
  "published-on"?: string;
  "created-by"?: string;
  "updated-by"?: string;
  "published-by"?: string;
}
/**
 * This interface was referenced by `undefined`'s JSON-Schema
 * via the `definition` "imageRef".
 */
export interface WebflowImageRef {
  fileId: string;
  url: string;
  alt?: string;
}
/**
 * This interface was referenced by `undefined`'s JSON-Schema
 * via the `definition` "mapFieldsWrite".
 */
export interface WebflowMapFieldsWrite {
  rowyid?: string;
  /**
   * Top-down minimap - longest side should be at least 1024px
   */
  minimap?: string;
  minimapurl?: string;
  /**
   * Map width in elmos
   */
  width?: number;
  /**
   * Map height in elmos
   */
  height?: number;
  /**
   * Downlink to BAR CDN
   */
  downloadurl?: string;
  /**
   * Main Title / Slogan / Tagline - not the name of the map.
   */
  title?: string;
  /**
   * Extra optional subtitle to support the main Title.
   */
  subtitle?: string;
  /**
   * Long-text for describing the map, gameplay, and unique features
   */
  description?: string;
  /**
   * The mapper that made this map
   */
  author?: string;
  /**
   * Unique Sketchfab Identifier that will be used if there is a 3D sketchfab version available.
   */
  sketchfabcode?: string;
  /**
   * Main Background image with overview of the map in-game - Usually low perspective
   */
  "bg-image"?: string;
  /**
   * Transparant image that fully shows the entire map in-game - borders/map extensions should be off, and/or be removed with an image-editor or background remover.
   */
  "perspective-shot"?: string;
  "more-images"?: string[];
  "wind-min"?: number;
  "wind-max"?: number;
  "tidal-strength"?: number;
  /**
   * Maximum players or startpositions for this map
   */
  "max-players"?: number;
  /**
   * Total amount of teams that can spawn / amount of (max.) preset startboxes or amount of AllyTeams.
   */
  "team-count"?: number;
  /**
   * store json with all sync related state serialized
   */
  syncstate?: string;
  /**
   * Simple textfield which should hold "gametype1, gametype2" - the simple solution for GameTypes
   */
  "game-types"?: string;
  /**
   * Reference Field for "Map Tags" which should hold the "itemID", "itemID" when linking multiple tags to this map
   */
  "game-tags-ref-2"?: string[];
  "mini-map"?: string;
  /**
   * Metal spots layout for map - ideally in transparant PNG - though black background - white metal is also fine.
   */
  "metal-map"?: string;
  /**
   * PNG heightmap - probably needs converting to regular 8-bit PNG
   */
  "height-map"?: string;
  /**
   * Surface of the map (W * H)
   */
  mapsize?: number;
  name: string;
  slug: string;
  _archived: boolean;
  _draft: boolean;
}
